### ISSUE TITLE
doubt for not tunneling

### ISSUE THREAD

**Issue by beckmx** [nabto/nabto-esp32cam#4]
Hello guys, I was just wondering, if I dont want to tunnel and only show the camera running on RTOS, what pieces could I take out?

**Comment by crgregersen** [comment]
You don't have to take anything out. The tunnel is just tunneling the webserver which feeds the video stream as a mjpeg stream. The webserver can be access on the IP address of the board on port 8081. The IP address can be found in the log when the camera is starting (with the monitor command). So if you find the ip adresse in your browser you type http://<ipaddress>:8081/
